### ISSUE TITLE
[Feature]: Renderer 함수 및 object 그리기.

### ISSUE THREAD

**Issue by devJgo** [devJgo/miniRT#18]
Package name: Renderer

### **Overview**

Objects들을 Render할 것입니다. mandatory의 기본 objects들은 다음 세가지 입니다. 

1. Sphere
2. Plane
3. Cylinder

1 ~ 3 순서대로 구현할 예정입니다. 
- [x] Sphere
- [x] #21 Plane
- [x] Cylinder

### **Describe the solution you'd like**

main -> renderer -> obj_list를 확인한 후 해당 object를 render하는 방식. 

각 object마다 file하나씩을 배정받습니다.

**Comment by idealflower-k** [comment]
#21 에서 plane object 구현
